version: "3.7"

services:

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: go_api
    ports:
      - 8080:8080
    volumes:
      - ./api:/go/src/app
    tty: true

  postgres_db:
    image: postgres:14
    container_name: postgres
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER='hoge'
      - POSTGRES_PASSWORD='root'
      - POSTGRES_DB='db'
volumes:
  db-store: